name: shell-commands
on:
  - push
env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
jobs:
  run-shell-commands:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.1.9
    - name: Terraform init
      run: terraform init 
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform plan
      run: terraforn plan 
    - name: echo string
      run: echo "Hello"
    - name: Multi line string
      run: |
        pwd
        node -v
        ls -a
        whoami
    - name: python shell-commands
      run: |
        import platform
        print (platform.processor())
      shell: python
  run-windows-commands: 
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: Directory
        run: pwd
        shell: bash